### ISSUE TITLE
how to adapt to discrete action space

### ISSUE THREAD

**Issue by Howuhh** [nicklashansen/tdmpc#1]
Hi! First of all, thanks for such an interesting and well written paper!

For my experiments, I would really like to try this approach on [Crafter](https://github.com/danijar/crafter) to compare it with DreamerV2. The problem is that Crafter only supports discrete action space.

I'm mostly familiar with model-free algorithms, so it's not quite obvious to me how this algorithm can be adapted. As far as I know MCTS is used for discrete action space, but writing it efficiently in python is a challenge. Is it reasonable to try to just change the distribution in CEM from normal to categorical and sample from it? Could it work?

**Comment by nicklashansen** [comment]
Hi, glad to hear that you're interested in our work! At this time, for discrete action spaces I think you might be better off starting with an MCTS-based method (e.g. MuZero/EfficientZero) and then augmenting that implementation with components from TD-MPC, e.g. the latent prediction loss and our (comparably) computationally efficient value learning. However, that approach would be rather experimental (but certainly interesting!).
