### ISSUE TITLE
Multimodal data as input to the model

### ISSUE THREAD

**Issue by SergioArnaud** [nicklashansen/tdmpc#10]
Hi, congratulations on the amazing work!

I wanted to ask a question, the paper mentions that multimodal data [RGB + proprioception] can be used as input of the model

In the code, the observations are sent to an [encoder](https://github.com/nicklashansen/tdmpc/blob/5c8c656a767aa6966ca93d9c109748ed01780fe3/src/algorithm/helper.py#L98) that process them in different ways depending if it's pixels or another modality, nevertheless I'm not sure that any of those options apply to multimodal data containing both pixels and state information. Given the experiments you made in the paper, how would you recommend processing such data in the encoder?

**Comment by nicklashansen** [comment]
Hi, thank you for your interest. We recently open-sourced an extension to the TD-MPC algorithm which takes multimodal data (pixels + state) inputs by default. It is available here: https://github.com/facebookresearch/modem/blob/6cee94def92b910a3fe122a10dcec1330c3519c3/algorithm/tdmpc.py#L37
Modalities are fused by projecting features from each modality into a low-dim space and summing them. Feel free to re-open if you have additional questions!
