### ISSUE TITLE
Implementation in Openai Atari gym

### ISSUE THREAD

**Issue by zrbak** [nicklashansen/tdmpc#12]
Firstly, thank you for the awesome paper!

I was trying to implement this using OpenAI's Atari gym instead of the physics sims and I was having some trouble getting it set up. Could you give me some tips on how I should modify the functions to make it work? Thanks!

**Comment by nicklashansen** [comment]
Thank you for your interest. Adapting TD-MPC to discrete action spaces might not be straight-forward since the MPC framework is designed for continuous action spaces. See also https://github.com/nicklashansen/tdmpc/issues/1.
