### ISSUE TITLE
[Q]: Termination Prevention Logic

### ISSUE THREAD

**Issue by ArashAhmadian** [nicklashansen/tdmpc#14]
Hello, 

So I am wondering how is it ensured that a termination state isn't reached when actions are getting generated by in planning? as enforced at `assert len(episode) == cfg.episode_length` in `train.py`

I'm thinking about potentially removing such condition which would require some code changes in different places but first want to ensure I have the right idea : )

**Comment by nicklashansen** [comment]
Hi, thanks for your interest!

Our codebase currently assumes that all episodes are of equal length, but it should be perfectly fine to modify the codebase to support episodes of variable length. You'd mainly have to modify the replay buffer and value function. If you need to access termination signals during planning you could add a separate prediction head for that, similar to how rewards are predicted.

Feel free to share your progress on this, and let me know if any other questions arise!

**Comment by nicklashansen** [comment]
@ArashAhmadian I realize this has been a while, but I just wanted to give you an update. I have now added support for variable episode lengths + termination logic in our TD-MPC2 codebase, see commit https://github.com/nicklashansen/tdmpc2/commit/fabf01a5ec92e7cc5793ee9cbbced881a9c13798#commitcomment-136456315 if interested. Closing this issue, but feel free to re-open if you have any questions!
