### ISSUE TITLE
How to visualize the evaluation process？

### ISSUE THREAD

**Issue by zsn2021** [nicklashansen/tdmpc#15]
def evaluate(env, agent, num_episodes, step, env_step, video):
	"""Evaluate a trained agent and optionally save a video."""
	episode_rewards = []
	for i in range(num_episodes):
		obs, done, ep_reward, t = env.reset(), False, 0, 0
		if video: video.init(env, enabled=(i==0))
		while not done:
			action = agent.plan(obs, eval_mode=True, step=step, t0=t==0)
			obs, reward, done, _ = env.step(action.cpu().numpy())
			ep_reward += reward
			if video: video.record(env)
			t += 1
		episode_rewards.append(ep_reward)
		if video: video.save(env_step)
	return np.nanmean(episode_rewards)
Hello, may I ask how to incorporate visualization into the evaluation process, such as using "env. render()" in Gym.

**Comment by nicklashansen** [comment]
Hi, thank you for your interest! Running the training script with `save_video=true` will log videos to wandb. The codebase does not log videos locally, but if that is what you are after, you can add it by changing the line here https://github.com/nicklashansen/tdmpc/blob/b8e945ed4368084e2a370dd239d668e3d9d95bf3/src/logger.py#L76 to instead save locally with e.g. imageio.
