### ISSUE TITLE
Discrepancy between code and implementation regarding the planned action

### ISSUE THREAD

**Issue by odelalleau** [nicklashansen/tdmpc#16]
In the paper, Alg. 1 ends with:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/507137/231180930-7ba5c734-c6c4-4a29-9abf-efa054ca9b0d.png">
where the mean action is given in eq. 4 by a weighted average of the top k actions:
<img width="164" alt="image" src="https://user-images.githubusercontent.com/507137/231181083-f73c3815-78f8-46ce-96e4-32bf2b98bdb9.png">

However, the code at https://github.com/nicklashansen/tdmpc/blob/b8e945ed4368084e2a370dd239d668e3d9d95bf3/src/algorithm/tdmpc.py#L145 seems to be selecting a single action (randomly sampled from the top k actions, with a weight proportional to the action score) rather than using the weighted mean from the equation above. Here's the full excerpt:
```python
		actions = elite_actions[:, np.random.choice(np.arange(score.shape[0]), p=score)]
		self._prev_mean = mean
		mean, std = actions[0], _std[0]
		a = mean
		if not eval_mode:
			a += std * torch.randn(self.cfg.action_dim, device=std.device)
		return a
```

Could you please confirm that my understanding is correct, and clarify the intended behavior here?

**Comment by nicklashansen** [comment]
Correct. Good catch! Generally speaking, I do not expect these two implementations to differ much in terms of outcome, and I seem to recall that we in fact tried both. However, the latter (in code) would intuitively be more likely to execute a good (high value) trajectory if the planning either fails to converge or is terminated prematurely (both with and without the action noise added during training).

**Comment by odelalleau** [comment]
Makes sense, thanks for clarifying!
