### ISSUE TITLE
I encountered some problems during training

### ISSUE THREAD

**Issue by like2000522** [nicklashansen/tdmpc#17]
I saw the paper and code you wrote online, and it was excellent. I also found it very interesting, so I downloaded it and ran it. But after my training exceeds 50000 steps, this error message will appear. Not for those below 50000 steps. I'm not sure if you have encountered this problem during your scientific research. If you could answer my question, I would greatly appreciate it

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x4 and 20x256)

**Comment by like2000522** [comment]
Oh, it's my computer problem. I've already resolved it. I'm sorry to bother you

**Comment by nicklashansen** [comment]
Great that you solved it! Let me know if you run into any other issues :-)
