### ISSUE TITLE
Package for Plots

### ISSUE THREAD

**Issue by MianchuWang** [nicklashansen/tdmpc#18]
Hi, Nicklas,

The figures in the paper (Figure 1, Figure 3, Figure 4) are very nice. Could you tell me which package you use to plot them?

Best Regards,
Mianchu

**Comment by nicklashansen** [comment]
Hi Mianchu, I use [seaborn](https://seaborn.pydata.org/) for data visualization. You can customize plots to your liking, but IMO seaborn plots look great even with default settings.
