### ISSUE TITLE
[Q]: Manipulator tasks and visualization

### ISSUE THREAD

**Issue by Ozzey** [nicklashansen/tdmpc#19]
Hello! 

In the paper, you mentioned TD-MPC can be used for manipulators for tasks such as bin picking and hammer. Do you have any implemented code or trained model for this?

I would like to know if there are any documentations on using visualizing the tasks once the model is already trained, for example I have a trained reacher-easy model and I wanted to visualize it (other than visualizing it during training).

**Comment by nicklashansen** [comment]
Hi @Ozzey , thanks for reaching out! Support for Meta-World tasks is available in branch [metaworld](https://github.com/nicklashansen/tdmpc/tree/metaworld), which includes the two tasks that you reference. Re: visualization, you could load your checkpoint and run the evaluation code provided in `train.py` although that would require a little bit of coding yourself.

If you're not limited to using TD-MPC1, you might consider switching over to TD-MPC2 (available [here](https://github.com/nicklashansen/tdmpc2)) which does have all of the functionality that you are requesting here. We released 300+ model checkpoints that you can download and visualize by following the example provided [here](https://github.com/nicklashansen/tdmpc2?tab=readme-ov-file#evaluation).

**Comment by Ozzey** [comment]
Thank you for the response! I'll try out TD-MPC2.
