### ISSUE TITLE
Other envs

### ISSUE THREAD

**Issue by Lvwenzhou** [nicklashansen/tdmpc#2]
Hi, i'm sorry to be a bother. I wonder how i run my own env in your code. Beacuse i found that there is  ` if (domain, task) in suite.ALL_TASKS:`.

**Comment by nicklashansen** [comment]
Our repo uses DMControl which follow the standard gym api, so it should be fairly straightforward to extend to other environments. You will need to modify the `make_env` function at https://github.com/nicklashansen/tdmpc/blob/96cb7036ecf06f75d5ffd64a0454bbab7d0d3e17/src/env.py#L246 such that it uses your own environment + wrappers. You might also need to normalize the action space to [-1, 1] if it is not already normalized.

**Comment by Lvwenzhou** [comment]
thank you so much!
