### ISSUE TITLE
Intuition behind using LayerNorm in Q function?

### ISSUE THREAD

**Issue by mch5048** [nicklashansen/tdmpc#5]
Hi, while I was reading through the code implementation,  I found that LayerNorm is only used after the input layer of Q-network.
What is the reason for this? 

I guess it stabilizes the Q-value estimation that is susceptible to wrong value estimations.

Thanks in advance!

**Comment by nicklashansen** [comment]
LayerNorm is not super critical to our implementation, but you're right that it does tend to help stabilize things. Our architecture is loosely based on that of https://github.com/denisyarats/drq/blob/master/drq.py which also uses LayerNorm.

**Comment by yueyang130** [comment]
Hi, @mch5048 @nicklashansen .

You may refer to this paper in NeurIPS 2023 [Understanding, Predicting and Better Resolving Q-Value Divergence in Offline-RL](https://arxiv.org/abs/2310.04411) to find out why LayerNorm helps in reducing Q-value error in Q function.
