### ISSUE TITLE
Question about base.device

### ISSUE THREAD

**Issue by pickxiguapi** [nicklashansen/tdmpc#6]
Hi! thanks for this excellent paper and it inspired me a lot!

In my experiment, I'm confused about the device setting in `cfg.py`:

https://github.com/nicklashansen/tdmpc/blob/96cb7036ecf06f75d5ffd64a0454bbab7d0d3e17/src/cfg.py#L45

I don't understand why we need to make pixel's environment(`modality=='pixels'`) based on cpu and state's environment(`modality=='state'`) based on gpu(cuda), is there any special purpose for this setting?

**Comment by nicklashansen** [comment]
Hi, sampling is slightly faster when the replay buffer is entirely in GPU memory. This is feasible for state observations but likely not pixel observations, depending on your hardware. I'm closing the issue; feel free to reopen if you have further questions!
