### ISSUE TITLE
Why I can't save the video?

### ISSUE THREAD

**Issue by Bailey-24** [nicklashansen/tdmpc#7]
I ran the command `python src/train.py task=dog-run save_video=True save_model=True`
When finished the train, I only got the `model.pt`, there are not video saved.

My platform is ubuntu20.04

**Comment by nicklashansen** [comment]
Hi, we only save videos to wandb by default. You'd need to either link a wandb account or modify the line here https://github.com/nicklashansen/tdmpc/blob/96cb7036ecf06f75d5ffd64a0454bbab7d0d3e17/src/logger.py#L76 to use a different library (e.g. imageio) for saving videos. I'm closing this issue but feel free to reopen if you have additional questions.
