### ISSUE TITLE
Why don't have Meta-World task in the task.txt?

### ISSUE THREAD

**Issue by 945716994** [nicklashansen/tdmpc#9]
I saw that Meta-World is used in the paper, but it doesn't seem to be in the code. How do I change the code if I want to use a Meta-World environment?

**Comment by nicklashansen** [comment]
Hi, thank you for your interest. I have added support for Meta-World tasks in a new branch: https://github.com/nicklashansen/tdmpc/tree/metaworld. Please note that this branch has not been fully tested yet, but should approximately reproduce our results.
